export default {
    port: 3000,
    env: 'dev',
    access_token_expire: '10m',
    refresh_token_expire: '30d',
    refresh_token_secret: 'refresh_token_secret',
    access_token_secret: 'access_token_secret',
    dbUri: '',
    mail_user: '',
    mail_password: '',
    mail_port: 2525,
    mail_host: '',
    session_secret: '',
    google_client_id: '',
    google_client_secret: '',
    google_callback_url: '',
};
